### ISSUE TITLE
Build fail for capacitor v5

### ISSUE THREAD

**Issue by vincentsartoko** [AppsFlyerSDK/appsflyer-capacitor-plugin#126]
Hi, when doing `gradlew bundleRelease`, it throws this error:

```
> Configure project :appsflyer-capacitor-plugin
could not found package.json from ENV variable
searching for package.json recursively
node_modules directory not found in any parent directories.

* What went wrong:
A problem occurred evaluating project ':appsflyer-capacitor-plugin'.

> Cannot get property 'androidSdkVersion' on null object
```

**Comment by vincentsartoko** [comment]
Found the issue, when android file is not on the same directory as the frontend file, it will throw error due to file not found.

Maybe try to modify this line? `node_modules/appsfluer-capacitor-plugin/android/build.gradle`

```
String getPackageJsonPath() {
    return findProperty("APPSFLYER_PACKAGE_JSON") ?: "$rootDir/../node_modules/appsflyer-capacitor-plugin/package.json"
}
```

**Comment by Dani-Koza-AF** [comment]
The goal of `getPackageJsonPath()` is to find the path to the `package.json` file in order to import the correct configuration for AppsFlyer's Android SDK. Thank you for your suggestion but locating `build.gradle` is not the goal so it's not a relevant modification.
I am working on a solution that will cover as much as possible paths for irregular project structures in order to fetch the `package.json` file, and it will be released next week. 
If you wish, regardless of the new solution that will be introduced, you may easily add the property `APPSFLYER_PACKAGE_JSON` (which represents a string which is the path to `package.json`) to `android/variables.gradle` file amongst the various properties there. 

*_`APPSFLYER_PACKAGE_JSON` will be changed to `APPSFLYER_PACKAGE_JSON_PATH` in next release_

**Comment by Dani-Koza-AF** [comment]
New version v6.15.2 will be release tomorrow, with a improvements according to your request and another possible fallback solution will be described.
