### ISSUE TITLE
Send SKAN postback copies directly to AppsFlyer (iOS 15+)

### ISSUE THREAD

**Issue by sultanmyrza** [AppsFlyerSDK/appsflyer-capacitor-plugin#24]
Hello,
AppsFlyer team does this plugin need updates to make sure it works on iOS 15+? Related [docs](https://support.appsflyer.com/hc/en-us/articles/4402320969617-Send-iOS-15-SKAN-postbacks-directly-to-AppsFlyer-).

We are getting this error at app start
```
SKAdNetwork: Error while updating conversion value: Error Domain=SKANErrorDomain Code=10 "(null)"
2022-07-03 16:18:03.307836+0600 App[70753:2527474] [Attribution] updatePostbackConversionValue returned error: The operation couldn’t be completed. (SKANErrorDomain error 10.).
```

[Here](https://github.com/numbersprotocol/capture-lite/blob/master/package.json#L64) is the plugin version we are using.
[Here](https://github.com/numbersprotocol/capture-lite/blob/master/src/app/shared/app-flyer/apps-flyer.service.ts#L28) is our init apps flyer SDK logic.

**Comment by ge-af** [comment]
Hi @sultanmyrza ,

Thank you for reaching out!

We would kindly ask you to submit a support ticket to support@appsflyer.com in order to get optimal support.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
